# Generated by Django 3.1.7 on 2021-04-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=20),
        ),
    ]
